name: 'Sentry Artifacts'
description: 'Handles uploading coverage/test artifacts to codecov'

inputs:
  files:
    description: "Path to coverage file(s) - comma separated for multiple files"
    default: ".artifacts/*.coverage.xml"
    required: true
  type:
    description: "The type of change (frontend, backend)"
    default: "backend"
    required: false

runs:
  using: "composite"
  steps:
    - name: Upload to codecov
      uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # v3.1.1
      with:
        flags: ${{ inputs.type }}
        files: ${{ inputs.files }}
        verbose: true
      continue-on-error: true
